-- =============================================
--  Supabase SQL — Visitor Globe ke liye
--  Isko Supabase → SQL Editor mein paste karo
-- =============================================

create table if not exists visitors (
  id bigint generated by default as identity primary key,
  country text not null default 'Unknown',
  city text not null default 'Unknown',
  lat double precision not null default 0,
  lng double precision not null default 0,
  visited_at timestamptz not null default now()
);

-- Row Level Security: sabko insert + select ki permission
alter table visitors enable row level security;

create policy "Anyone can insert visitors"
  on visitors for insert
  with check (true);

create policy "Anyone can view visitors"
  on visitors for select
  using (true);
